<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'error', language 'zh_tw', branch 'MOODLE_23_STABLE'
 *
 * @package   error
 * @copyright 1999 onwards Martin Dougiamas  {@link http://moodle.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['alreadyloggedin'] = '您已經以{$}身分登入，您要以不同的用戶身分登入之前，需要先登出。';
$string['authnotexisting'] = 'autorization插件不存在';
$string['backupcontainexternal'] = '此備份檔案包含外部Moodle的網絡，它在本地沒有配置。';
$string['backuptablefail'] = '備份的資料表不能順利安裝！';
$string['blockcannotconfig'] = '此區塊不支持全局配置';
$string['blockcannotinistantiate'] = '區塊無法實例化';
$string['blockcannotread'] = '無法為 blockid = {$} 讀取資料';
$string['blockdoesnotexist'] = '這一區塊不存在';
$string['blockdoesnotexistonpage'] = '這區塊 (id={$a->instanceid})不存在於這一頁 ({$a->url})。';
$string['blocknameconflict'] = '命名衝突：區塊 {$a->name}和現存的區塊 {$a->conflict}有相同的標題!';
$string['cannotaddcoursemodule'] = '無法新增一課程模組';
$string['cannotaddcoursemoduletosection'] = '無法新增一課程模組到這章節';
$string['cannotaddmodule'] = '{$a} 模組不能新增到這模組清單!';
$string['cannotaddnewmodule'] = '無法新增一新模組f {$a}';
$string['cannotaddrss'] = '你沒有權限新增 rss feeds';
$string['cannotaddthisblocktype'] = '你不能新增一 {$a} 區塊到這一頁';
$string['cannotassignrole'] = '在課程中無法指派角色';
$string['cannotassignrolehere'] = '你不能在這情境 ({$a->context})指派中這一角色 (id = {$a->roleid})';
$string['cannotassignselfasparent'] = '無法指派自己為上層';
$string['cannotcallscript'] = '你無法以此方式呼叫腳本';
$string['cannotcallusgetselecteduser'] = '你不能呼叫 user_selector::get_selected_user，若多重選擇為真';
$string['cannotcreatebackupdir'] = '無法建立備分資料夾。網站管理員需要修復檔案權限';
$string['cannotcreatecategory'] = '無法建立類目';
$string['cannotcreategroup'] = '無法建立群組';
$string['cannotcreatelangbase'] = '無法建立基本語言目錄';
$string['cannotcreatelangdir'] = '無法建立語言資料夾。';
$string['cannotcreateorfindstructs'] = '無法建立這一課程的分節結構';
$string['cannotcreatepopupwin'] = '無法建立彈出式視窗';
$string['cannotcreatesitedir'] = '無法建立網站資料夾。這網站管理員需要修復這檔案權限。';
$string['cannotcreatetempdir'] = '無法建立暫存資料夾。';
$string['cannotcreateuploaddir'] = '不能建立上傳的資料夾。網站的管理員需要修復該檔案的權限。';
$string['cannotcustomisefiltersblockuser'] = '你不能在用戶或區塊的情境下，自行定義過濾器的設定。';
$string['cannotdeletebackupids'] = '無法刪除先前的備份檔';
$string['cannotdeletecategorycourse'] = '課程 \'{$a}\' 無法被刪除';
$string['cannotdeletecategoryquestions'] = '無法從類目 \'{$a}\'刪除試題';
$string['cannotdeletecourse'] = '你沒有權限刪除這一課程';
$string['cannotdeletecustomfield'] = '無法刪除自訂欄位資料';
$string['cannotdeletedir'] = '無法刪除 ({$a})';
$string['cannotdeletefile'] = '無法刪除這一檔案';
$string['cannotdeleterole'] = '它無法被刪除，因為 {$a}';
$string['cannotdeleterolewithid'] = '不能刪除編號{$a}的角色';
$string['cannotdeletethisrole'] = '你不能刪除這一角色，因為它是由系統所使用，或因為它是有管理員權限的最後角色。';
$string['cannotdownloadcomponents'] = '無法下載元件。';
$string['cannotdownloadlanguageupdatelist'] = '無法從download.moodle.org下載語言清單';
$string['cannotdownloadzipfile'] = '無法下載 ZIP 檔案。';
$string['cannoteditcomment'] = '這評論不是你的，不可以刪除!';
$string['cannoteditcommentexpired'] = '你不能編輯這個，時間已經超過。';
$string['cannoteditpostorblog'] = '你不可以張貼或刪除部落格';
$string['cannoteditsiteform'] = '你不可以使用這一表格編輯這網站的課程';
$string['cannotedityourprofile'] = '抱歉，你無法編輯自己的';
$string['cannotfindcategory'] = '無法以ID - {$a}從資料庫找到類別紀錄';
$string['cannotfindcomponent'] = '找不到元件。';
$string['cannotfindcontext'] = '找不到脈絡';
$string['cannotfindcourse'] = '找不到課程';
$string['cannotfinddocs'] = '找不到 "{$a}" 語言的文件檔';
$string['cannotfindgradeitem'] = '無法找到評分項目';
$string['cannotfindgroup'] = '無法找到群組';
$string['cannotfindhelp'] = '找到 "{$a}"語言的幫助說明檔';
$string['cannotfindinfo'] = '找不到 "{$a}"的資訊';
$string['cannotfindlang'] = '找不到 "{$a}"語言包';
$string['cannotfindteacher'] = '找不到教師';
$string['cannotfinduser'] = '找不到名字為 "{$a}"的用戶';
$string['cannotgetblock'] = '無法從資料庫中檢索區塊';
$string['cannotgetcats'] = '不能得到分類紀錄';
$string['cannotgetdata'] = '無法取得資料';
$string['cannotgradeuser'] = '無法對這一用戶評分';
$string['cannothaveparentcate'] = '課程類目不能有上層';
$string['cannotimport'] = '無法匯入';
$string['cannotimportformat'] = '很抱歉，此格式導入尚未實現！';
$string['cannotimportgrade'] = '無法匯入成績';
$string['cannotinsertgrade'] = '沒有課程編號，無法插入計分項目';
$string['cannotinsertrate'] = '無法插入新的評比 ({$a->id} = {$a->rating})';
$string['cannotinsertrecord'] = '不能插入新紀錄編號{$a}';
$string['cannotmailconfirm'] = '無法送出確認要變更密碼的email';
$string['cannotmanualctrack'] = '活動沒有提供人工完成度追蹤';
$string['cannotmodulename'] = '不能在已建立的導覽列中取得模組名稱';
$string['cannotmoduletype'] = '不能在已建立的導覽列中取得模組類型';
$string['cannotmoverolewithid'] = '不能移除編號 {$a}的角色';
$string['cannotopencsv'] = '無法開啟 CSV 檔';
$string['cannotopenfile'] = '無法開啟檔案({$a})';
$string['cannotopenforwrit'] = '無法開啟({$a})來寫入';
$string['cannotopentemplate'] = '無法開啟樣版檔案({$a})';
$string['cannotopenzip'] = '無法開啟壓縮檔，可能是64bit作業系統上的zip擴展的臭蟲';
$string['cannotoverridebaserole'] = '無法覆蓋基本角色權限';
$string['cannotoverriderolehere'] = '你不允許覆蓋這角色(id = {$a->roleid}) 在這情境({$a->context})';
$string['cannotreadfile'] = '無法閱讀檔案({$a})';
$string['cannotreadtmpfile'] = '無法閱讀暫存檔案';
$string['cannotreaduploadfile'] = '無法閱讀上載的檔案';
$string['cannotremovefrommeta'] = '無法從這後設課程中移除這選出的課程';
$string['cannotresetguestpwd'] = '你無法重設訪客密碼';
$string['cannotresetmail'] = '無法重設密碼並寄給你';
$string['cannotresetthisrole'] = '無法重設這一角色';
$string['cannotrestore'] = '發生了錯誤，無法完成回存！';
$string['cannotrestoreadminorcreator'] = '你必須是一個開課者或管理員，才可回存到新課程！';
$string['cannotrestoreadminoredit'] = '你必須是編輯老師或管理員，才可回存到所選的課程！';
$string['cannotsavemd5file'] = '無法儲存 md5 檔案。';
$string['cannotsavezipfile'] = '無法儲存 ZIP 檔案。';
$string['cannotunzipfile'] = '無法解壓縮檔案。';
$string['cannotviewprofile'] = '您不能看這位使用者的個人資料';
$string['componentisuptodate'] = '元件已經是最新的了。';
$string['confirmsesskeybad'] = '抱歉，您的session key 無法確認能進行這個動作,這個安全性功能是為了預防以您的帳號進行意外或惡意執行一些重要功能,請確認您真的要執行這個功能。';
$string['couldnotassignrole'] = '指定角色給您時發生了一個嚴重但是不明的錯誤。';
$string['coursegroupunknown'] = '與群組 {$a} 對應的課程沒被指定';
$string['csvcolumnduplicates'] = '檢測到重複的欄位';
$string['csvemptyfile'] = '這CSV檔是空的';
$string['csvfewcolumns'] = '欄位數不足，請檢查分隔符號設定';
$string['csvweirdcolumns'] = '不正確的CSV檔格式：欄位數目不固定！';
$string['dbupdatefailed'] = '更新資料庫失敗';
$string['downloadedfilecheckfailed'] = '下載檔案檢查錯誤。';
$string['duplicateusername'] = '使用者名稱重複：跳過紀錄';
$string['errorcleaningdirectory'] = '清除"{$a}"目錄時發生錯誤';
$string['errorcopyingfiles'] = '複製檔案時發生錯誤';
$string['errorcreatingdirectory'] = '建立目錄 "{$a}" 時發生錯誤';
$string['errorcreatingfile'] = '建立檔案 "{$a}" 時發生錯誤';
$string['erroronline'] = '錯誤發生在第 {$a} 行';
$string['errorreadingfile'] = '讀取檔案 "{$a}" 時發生錯誤';
$string['errorunzippingfiles'] = '解壓縮檔案時發生錯誤';
$string['fieldrequired'] = '"{$a}" 是必填的欄位';
$string['filenotfound'] = '抱歉,指定的檔案找不到';
$string['forumblockingtoomanyposts'] = '您已經超過這個討論區的張貼限制。';
$string['groupalready'] = '使用者已隸屬於群組 {$a}';
$string['groupexistforcourse'] = '這課程已經有"{$a}"群組了';
$string['groupnotaddederror'] = '群組 "{$a}" 新增失敗';
$string['groupunknown'] = '群組{$a}與指定的課程不相關';
$string['guestnoeditprofile'] = '訪客無法編輯個人資料';
$string['guestnoeditprofileother'] = '不能編輯訪客個人資料';
$string['hackdetected'] = '偵測到駭客攻擊!';
$string['invalidcommentarea'] = '無效的評論區域';
$string['invalidcommentid'] = '無效的評論編號';
$string['invalidcommentitemid'] = '無效的試題編號';
$string['invalidcommentparam'] = '無效的評論參數';
$string['invalidcomponent'] = '無效的元件名稱';
$string['invalidconfirmdata'] = '無效的確認資料';
$string['invalidcontext'] = '無效的情境';
$string['invalidcourse'] = '無效的課程';
$string['invalidcoursenameshort'] = '無效的課程簡稱';
$string['invaliddata'] = '提交的資料是無效的';
$string['invaliddevicetype'] = '無效的設備類型';
$string['invalidentry'] = '無效的條目';
$string['invalidevent'] = '無效的事件';
$string['invalidfieldname'] = '"{$a}" 不是合法的欄位名稱';
$string['invalidfiletype'] = '"{$a}" 不是合法的檔案型態';
$string['invalidipformat'] = 'IP 格式錯誤';
$string['invalidmd5'] = '無效的 md5';
$string['invalidmodule'] = '無效的模組';
$string['invalidmoduleid'] = '無效模組編號： {$a}';
$string['invalidmodulename'] = '無效模組名稱： {$a}';
$string['invalidnum'] = '無效的數值';
$string['invalidoutcome'] = '不正確的核心能力編號';
$string['invalidpagesize'] = '無效的頁面大小';
$string['invalidpasswordpolicy'] = '無效的密碼管理辦法';
$string['invalidpaymentmethod'] = '無效的付款方式: {$a}';
$string['invalidratingarea'] = '無效的評比區域';
$string['invalidrequest'] = '無效的請求';
$string['invalidrole'] = '無效的角色';
$string['invalidroleid'] = '無效的角色編號';
$string['invalidscaleid'] = '無效的量尺編號';
$string['invalidsection'] = '課程模組紀錄包含無效的章節';
$string['invalidshortname'] = '這是無效的課程簡稱';
$string['invalidstatedetected'] = '一定出了差錯{$a}，這通常是不會發生。';
$string['invalidurl'] = '無效的URL網址';
$string['invaliduser'] = '無效的用戶';
$string['invaliduserfield'] = '無效的用戶欄位: {$a}';
$string['invaliduserid'] = '無效的用戶編號';
$string['invalidxmlfile'] = '"{$a}" 不是合法的XML檔案';
$string['iplookupfailed'] = '無法找到這個IP位址 {$a}的地理資訊';
$string['iplookupprivate'] = '無法顯示私有IP位址查詢結果';
$string['ipmismatch'] = '用戶IP位址不符合';
$string['listcantmovedown'] = '向下移動項目失敗，已經是在最後位置。';
$string['listcantmoveleft'] = '向左移動項目失敗，沒有找到父項目。';
$string['listcantmoveright'] = '向右移動項目失敗，沒有找到子項。您必須向下移動到另一個同類項中後才能向右移。';
$string['listcantmoveup'] = '已經是最上層了，無法再往上移動了!';
$string['listnochildren'] = '找不到下層項目';
$string['listnoitem'] = '找不到項目';
$string['listnopeers'] = '找不到同層項目';
$string['listupdatefail'] = '編輯列表層級時，DB操作失敗。';
$string['logfilenotavailable'] = '日誌無法使用';
$string['loginasnoenrol'] = '以其他身分登入連線時，不能選課或退選。';
$string['loginasonecourse'] = '您無法進入這個課程，在進入其他課程前，您必須先終止以其他身分登入的連線。';
$string['maxbytes'] = '這檔案大於檔案最大值';
$string['messagingdisable'] = '在這網站，簡訊功能是關閉的';
$string['missingfield'] = '欄位 "{$a}" 不存在';
$string['missingparameter'] = '缺少參數';
$string['missingrequiredfield'] = '缺少部份必填欄位';
$string['missinguseranditemid'] = '缺少用戶編號和項目編號';
$string['missingvarname'] = '缺少必要的變項名稱!';
$string['mnetlocal'] = '遠端MNET用戶不能在本地登入';
$string['moduledoesnotexist'] = '這模組不存在';
$string['moduleinstancedoesnotexist'] = '這模組的實例不存在';
$string['modulemissingcode'] = '模組 {$a} 缺少了執行這個功能所需要的代碼';
$string['multiplerecordsfound'] = '找到多筆紀錄，但應該只有一筆';
$string['multiplerestorenotallow'] = '不允許同時執行多個回存!';
$string['mustbeloggedin'] = '你必須登入才能做這個';
$string['mustbeteacher'] = '只有教師可以檢視這個頁面';
$string['needcopy'] = '你需要先複製某些東西!';
$string['needcoursecategroyid'] = '必須指定課程編號或類別';
$string['noadmins'] = '沒有管理員!';
$string['noblocks'] = '找不到區塊!';
$string['nocontext'] = '很抱歉，但此課程不是一個有效的環境';
$string['nodata'] = '沒有資料';
$string['noexistingcategory'] = '沒有現存的類別';
$string['nofile'] = '沒有指定檔案';
$string['nofiltersenabled'] = '沒有過濾器被啟用';
$string['nofolder'] = '需要的目錄不存在';
$string['noguest'] = '現在沒有訪客!';
$string['noinstances'] = '在本課程中沒有{$a}！';
$string['nologinas'] = '您不可以登入為此使用者';
$string['nonmeaningfulcontent'] = '沒有實質內容';
$string['noparticipants'] = '這一課程找不到參與者';
$string['noparticipatorycms'] = '抱歉，您沒有可以分享的課程模組。';
$string['nopermissions'] = '抱歉，但是您目前沒有權限執行({$a})';
$string['nopermissiontocomment'] = '你沒有權限去新增評論';
$string['nopermissiontodelentry'] = '你沒有權限去刪除他人的條目';
$string['nopermissiontoeditcomment'] = '你沒有權限編輯他人的評論';
$string['nopermissiontohide'] = '你沒有權限去隱藏';
$string['nopermissiontoimportact'] = '你沒有需要的權限去匯入活動到到這一課程。';
$string['nopermissiontolock'] = '你沒有權限去封鎖';
$string['nopermissiontomanagegroup'] = '你沒有權限去管理群組';
$string['nopermissiontorate'] = '你沒有權限去做評比';
$string['nopermissiontoshow'] = '你沒有權限去看這個!';
$string['nopermissiontounlock'] = '你沒有權限去解除封鎖';
$string['nopermissiontoupdatecalendar'] = '你沒有權限去更新行事曆事件';
$string['nopermissiontoviewgrades'] = '你沒有權限檢視成績';
$string['nopermissiontoviewletergrade'] = '你沒有權限檢視文字等第';
$string['nopermissiontoviewpage'] = '你沒有權限去檢視這一頁';
$string['nosite'] = '無法找到一個上層的課程';
$string['nositeid'] = '沒有網站編號';
$string['nostatstodisplay'] = '抱歉，目前沒有資料可以顯示。';
$string['notallowedtoupdateprefremotely'] = '你不能從遠端更新這一用戶的偏好';
$string['notavailable'] = '目前無法使用';
$string['notmemberofgroup'] = '你不是這一刻成群組的成員';
$string['notownerofkey'] = '你不是這一密鑰的擁有者';
$string['nousers'] = '沒有這一用戶!';
$string['onlyadmins'] = '只有管理者可以這麼做';
$string['onlyeditingteachers'] = '只有擁有修改權的教師才能使用此功能。';
$string['onlyeditown'] = '您只能修改您自己的資料';
$string['orderidnotfound'] = '找不到訂單編號{$a}';
$string['pagenotexist'] = '一個不明錯誤發生（嘗試存取不存在的頁面）';
$string['pleasereport'] = '我們知道在錯誤發生的時候您在試圖做什麼 如果您有充裕的時間，請讓我們知道錯誤發生當時您正要執行什麼操作：';
$string['pluginrequirementsnotmet'] = '外掛 "{$a->pluginname}" ({$a->pluginversion}) 無法安裝，它需要更新版本的 Moodle （目前您正使用 {$a->currentmoodle} ，需要 {$a->requiremoodle}）';
$string['processingstops'] = '處理程序停止！剩餘的紀錄資料將被忽略。';
$string['refoundto'] = '可以退款給 {$a}';
$string['refoundtoorigi'] = '退款到原始金額：{$a}';
$string['remotedownloaderror'] = '下載元件至伺服器失敗，檢查代理伺服器的設定、高度建議安裝PHP cURL，您必須手動下載<a href="{$a->url}">{$a->url}</a>，並且複製到伺服器"{$a->dest}" 解壓縮';
$string['remotedownloadnotallowed'] = '您的伺服器不允許下載元件（停用了 allow_url_fopen ）。<br /><br />您必須手動下載 <a href="{$a->url}">{$a->url}</a> ，然後複製到 "{$a->dest}" 並且解壓縮。';
$string['reportnotavailable'] = '這類型的報告只有網站課程可以使用';
$string['requireloginerror'] = '課程或活動無法使用';
$string['restore_path_element_missingmethod'] = '缺少回存方法 {$a} ，它必須由程式設計這定義';
$string['restore_path_element_noobject'] = '回存物件 {$a} 不是一個物件';
$string['restricteduser'] = '抱歉,您的目前帳號 {$a} 無權進行上述操作.';
$string['scheduledbackupsdisabled'] = '管理者已關閉排程備份功能';
$string['sendmessage'] = '寄送訊息';
$string['sessionerroruser'] = '您的連線時間已經超過，請重新登入。';
$string['sessionerroruser2'] = '影響您的登入連線的伺服器錯誤被查出了。請再登入或重新啟動您的瀏覽器。';
$string['sessionipnomatch'] = '抱歉，您的ip似乎與您初次登入時不符，這個安全性功能可預防駭客以您的身份竊取您登入此站的資料，一般使用者可能不會看到這個訊息，請向系統管理者詢問取得協助。';
$string['shortnametaken'] = '簡稱已經被其他課程所用';
$string['spellcheckernotconf'] = '沒有配置拼字檢察功能';
$string['statscatchupmode'] = '統計資料目前在 catchup 模式， {$a->daysdone} 天內的資料已經處理， {$a->dayspending} 天的資料等候中，請立刻整理！';
$string['statsdisable'] = '沒有啟動統計功能';
$string['tagdisabled'] = '標籤已被關閉';
$string['tagnotfound'] = '資料庫中找不到指定的標籤';
$string['themenotinstall'] = '沒有安裝這個主題背景';
$string['unenrolerror'] = '當試著將此人退選時，發生錯誤';
$string['unicodeupgradeerror'] = '抱歉，您的資料庫並非使用萬國字元，而這個版本的 Moodle 無法轉換您的資料庫，請先升級到 Moodle 1.7.x 並且透過管理頁面執行萬國字元轉換，接著您應該就可以升級為 Moodle {$a}';
$string['unknowaction'] = '不知名的行動';
$string['unknowcategory'] = '不明的類別';
$string['unknowformat'] = '不明的格式({$a})';
$string['unknowncontext'] = '這是不明的情境';
$string['unknowncourse'] = '不明的課程名稱： {$a}';
$string['unknowncourseidnumber'] = '不明的課程 ID "{$a}"';
$string['unknowncourserequest'] = '不明的開課申請';
$string['unknownfiletype'] = '不明的過濾器類型';
$string['unknowngroup'] = '不明的群組 "{$a}"';
$string['unknownmodulename'] = '不明的模組名稱';
$string['unknownrole'] = '不明的角色"{$a}"';
$string['unknownsortcolumn'] = '不明的排序欄位 {$a}';
$string['unknownuseraction'] = '很遺憾，我不明白這位使用者的活動';
$string['unknownuserselector'] = '不明的用戶挑選器';
$string['unknoworder'] = '不明的排序';
$string['unknowparamtype'] = '不明的參數類型： {$a}';
$string['unknowquestiontype'] = '不支援的題型 {$a}';
$string['unknowuploadaction'] = '不明的上傳動作({$a})';
$string['unspecifycourseid'] = '必須指明課程編號，簡稱或辨認編號';
$string['unsupportedevent'] = '不支援的事件類型';
$string['unsupportedstate'] = '不支援的完成度統計';
$string['unsupportedwebserver'] = '不支援網頁伺服器軟體 ({$a}) ，抱歉。';
$string['upgraderunning'] = '網站正在升級中，請稍後再試。';
$string['urlnotdefinerss'] = 'RSS feed 的網址沒有界定';
$string['useradmineditadmin'] = '只有管理員可以修改其他管理員的帳號';
$string['useradminodelete'] = '管理員帳號不能被刪除';
$string['userautherror'] = '不明的認證外掛';
$string['userauthunsupported'] = '不支援的認證外掛';
$string['useremailduplicate'] = '重複的位址';
$string['usernotaddederror'] = '使用者 {$a} 新增失敗- 未知的錯誤';
$string['usernotaddedregistered'] = '使用者 {$a} 新增失敗- 該帳號已註冊';
$string['usernotavailable'] = '您無法檢視該使用者的詳細資料';
$string['usernotdeletederror'] = '錯誤!尚未刪除使用者...';
$string['usernotdeletedmissing'] = '錯誤!尚未刪除使用者...無法找到使用者名稱';
$string['usernotdeletedoff'] = '尚未刪除使用者...不允許刪除';
$string['usernotincourse'] = '這一用戶沒有在此一課程!';
$string['usernotrenamedadmin'] = '無法修改管理者名稱';
$string['usernotrenamedexists'] = '使用者沒有更名，新的名稱重複。';
$string['usernotrenamedmissing'] = '使用者沒有更名，找不到舊的帳號。';
$string['usernotrenamedoff'] = '尚未修改使用名稱...不允許更名';
$string['usernotupdatedadmin'] = '尚未更新管理者帳號';
$string['usernotupdatederror'] = '尚未更新---錯誤';
$string['usernotupdatednotexists'] = '尚未更新---不存在';
$string['wrongdestpath'] = '錯誤的目的路徑。';
$string['wrongroleid'] = '不正確的角色編號!';
$string['wrongsourcebase'] = '錯誤的來源網址基礎。';
$string['wrongusernamepassword'] = '錯誤的用戶/密碼';
$string['wrongzipfilename'] = '錯誤的 ZIP 檔名。';
$string['wscouldnotcreateecoursenopermission'] = 'WS - 無法建立課程--沒有權限';
$string['wwwrootslash'] = '在config.php偵測到不正確的 $CFG->wwwroot ，它不可以包含尾隨的斜線。

請通知伺服器管理員。';
$string['xmldberror'] = 'XMLDB 錯誤!';
$string['youcannotdeletecategory'] = '您不能刪除類別
"{$a}"，因為您不能刪除這內容，也不能將它們移到別處。';
